### ISSUE TITLE
no map appear on 2.79b

### ISSUE THREAD

**Issue by yann-insa** [domlysz/BlenderGIS#159] opened 2019-03-19 19:57 UTC
Hi ,
I encounter a little problem, i add your addon in blender 2.79b on mac and install gdal.
When I try to make same thing of quick start, no map appear, I don't understand why, i try to increase clap to 1m to 25km but nothing seems to work. I don't have error. I can zoom and it seems to be upload new map.
It's never work, I'm sure it's my fault but I don't understand what is my mistable (I'm newbie on blender).

Sorry for my english, I'm from Lyon.

Thanks you in advance,
Best regards

**Comment by manwekk** [comment] 2019-03-20 10:03
Hi, I have absolutely same issue on 2.79b and 2.8 version. When I try load Basemap there is only white screen instead of map. There is also downloading progress when zooming.
![image](https://user-images.githubusercontent.com/48753820/54675868-3c594c80-4b21-11e9-857e-b357e17cc3c1.png)

**Comment by domlysz** [comment] 2019-03-20 20:39
@yann-insa, have you a white image that appears or nothing at all? What's the map source you trying to load? is the issue appears for every source? Have you check into Blender's console if there is any error message printed? 

@manwekk, are you also on Mac OS? Same questions about map source in question, some error message in the console?

 White image means the http request does not return any valid image stream, you can try to print urls of sent requests into Blender's console and test them into your web browser. For this, uncomment the line n°569 in the file core/basemaps/mapservice.py

**Comment by yann-insa** [comment] 2019-03-20 20:54
Hi domlysz,

It's appear with all source Map, WE have black Map and if i remember, i donner have any thing on console.
I try gdal installation ,some code on a issue that return 0 (is it ok ).
Thanks toi
Regards

**Comment by s-leger** [comment] 2019-03-20 21:03
Black maps issue may occur with cache file write issue, when another request fails and still is running.
Try restarting the computer.

**Comment by yann-insa** [comment] 2019-03-21 08:37
I have restart more than 2 times, I changed cache folder and it's same problem.
![Capture d’écran 2019-03-21 à 09 34 47](https://user-images.githubusercontent.com/48733886/54740831-c86c8200-4bbc-11e9-997a-6a2cddeeeecf.png)
![Capture d’écran 2019-03-21 à 09 36 59](https://user-images.githubusercontent.com/48733886/54740872-ea660480-4bbc-11e9-8d51-93ff007e1596.png)

**Comment by domlysz** [comment] 2019-03-21 08:38
Can you check if the cache file increase when basemaps is running. For example start basemaps with google sat and check if the file GOOGLE_SAT_WM.gpkg had his size increasing. This file is located into the cache folder you have defined in the addon's preferences.

If the size does not increase then there is something wrong with http request, can you tel me if this url works for you : http://mt0.google.com/vt/lyrs=s&x=1&y=1&z=1

If the size increase it means that valid image data are putted into it. As this cache file is a geopackage database, it can be opened directly in QGIS for checking it's content. If you don't know QGIS, can you send me the file I will examine it by myself.

Cache files can be safely deleted, BlenderGIS will recreate then. Maybe it can be useful if the database was corrupted, but I never encounter this case.

Finally if the cache has been correctly seeded then it means something wrong when the addon try to buid the mosaic from the tiles. If the blend file has been saved before starting basemap then the image mosaic will be written into the same folder. So you can check if this image is valid outside of Blender. If no, the image processing engine can be in cause here but if you have installed GDAL I don't believe both standard ImageIO engine and GDAL fails. You can check which image engines are available in the addon preferences in the list box "image processing engine". Do you see both ImageIO and GDAL or only ImageIO? If GDAL is correctly installed and available then you can select this engine to force it's use.

**Comment by domlysz** [comment] 2019-03-21 08:40
oh cross answer. Can you send me GOOGLE_SAT_WM.gpkg file, it seems there is some valid data into it !

**Comment by yann-insa** [comment] 2019-03-21 08:42
Hi,
you can find file, and i will test your precedent message, on chrome url works for me
[GOOGLE_SAT_WM.gpkg.zip](https://github.com/domlysz/BlenderGIS/files/2991302/GOOGLE_SAT_WM.gpkg.zip)

**Comment by domlysz** [comment] 2019-03-21 08:44
ok I can confirm to you that the cache if correctly seeding

**Comment by yann-insa** [comment] 2019-03-21 08:48
File cache will created at 9:42 (new folder) and size is stable at 335,8ko, don't increase.

How can I check Gdal install is ok? when i install with port my computer tell I don't have Xcode but compile each package seems to be okay (no error in terminal)

**Comment by domlysz** [comment] 2019-03-21 09:40
ok that's interesting. There is no issue with the cache at all, the size will increase if you try to fetch data in another area. Definitively the issue is related to this one #149 , in MAC Os imageIO are not correctly installed it's why you've been asked to install gdal. It seems gdal is correctly installed but there is something wrong in the process. It will be hard for me to solve this issue as I've never used a Mac at all and I can't have access to a MAC. So I need to investigate more to solve ImageIO installation on MAC, I think it will be easier than trying to solve the issue with GDAL code without having a MAC test machine.

**Comment by yann-insa** [comment] 2019-03-21 13:04
ok, so nothing to do now if I understand.
I will try on windows computer next WE
regards

**Comment by domlysz** [comment] 2019-03-21 13:26
I've just updated the code to report imageio loading error, can you try in your side and report me the error.

**Comment by domlysz** [comment] 2019-04-07 18:17
Can you please try again with the Blender28 branch, it must be fixed now.

**Comment by domlysz** [comment] 2019-04-20 08:40
please reopen if you still encounter this issue

**Closed by domlysz** 2019-04-20 08:40 UTC
Labels: mac

**Comment by yann-insa** [comment] 2019-04-20 16:48
Ok, no problem, thanks you for this update, i dont have my computer Mac
with this software, so i cant test its version.
Regards
