### ISSUE TITLE
SHP Export failure

### ISSUE THREAD

**Issue by HorribleGoat** [domlysz/BlenderGIS#297] opened 2020-03-18 22:50 UTC
# **Blender and OS versions**

version: 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: f1aa4d18d49d, type: Release
build date: 2019-12-04, 14:30:40
platform: Windows 10 64bit professional

PYTHON INTERACTIVE CONSOLE 3.7.4 (default, Aug 13 2019, 14:10:15) [MSC v.1916 64 bit (AMD64)]

installed GDAL and numpy from links @ installation instructions

# **Describe the bug**

Can not export .shp files

# **How to Reproduce**

imported basemap, selected area, imported some roads OSM data and tried to export that out.

# **Error message**

Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\io_export_shp.py", line 162, in execute
    if v.lstrip("-+").isdigit():
AttributeError: 'IDPropertyGroup' object has no attribute 'lstrip'

location: <unknown location>:-1

**Comment by domlysz** [comment] 2020-03-19 07:52
can you attach the blend file ?

**Comment by HorribleGoat** [comment] 2020-03-19 12:22
Yes of course!

[BlenderGisDebug.zip](https://github.com/domlysz/BlenderGIS/files/4354391/BlenderGisDebug.zip)

**Comment by HorribleGoat** [comment] 2020-03-19 12:31
Actually the classical thing happened. I updated Blender to the latest 2.82 release and now the export seems to work. I'll test it a bit to confirm.

**Comment by HorribleGoat** [comment] 2020-03-19 12:52
Ok so it worked once, Then I had to open up Blender 2.79 to use another addon that has not yet moved to 2.8 and after that the export no longer works.

**Comment by domlysz** [comment] 2020-03-19 18:17
must be fixed now https://github.com/domlysz/BlenderGIS/commit/b120a3103946397c0bc14b34b6764d2294a9c8ed

**Comment by HorribleGoat** [comment] 2020-03-20 07:17
After reinstalling the plugin I got 1 export out without errors but doing the next one give out this:

`Exception ignored in: <function Writer.__del__ at 0x000002BF9F758678>
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1104, in __del__
    self.close()
  File "C:\Users\HorribleGoat\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1125, in close
    self.__shapefileHeader(self.shp, headerType='shp')
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1299, in __shapefileHeader
    f.write(pack("<4d", zbox[0], zbox[1], mbox[0], mbox[1]))
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_export_shp.py", line 162, in execute
    if isinstance(v, float) or isinstance(v, int):
AttributeError: 'IDPropertyGroup' object has no attribute 'lstrip'

location: <unknown location>:-1

`

**Comment by HorribleGoat** [comment] 2020-03-20 07:22
I re added the plugin again and got 1 export out. It however seems to match the data I exported so that works.

![image](https://user-images.githubusercontent.com/13536770/77143563-45f6f680-6a8c-11ea-8100-446cd3ff84fe.png)

**Comment by HorribleGoat** [comment] 2020-03-20 07:23
Exporting the same data out of the same scene into the same file gets me this though:
```

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_export_shp.py", line 273, in execute
    fType = next( (f[1] for f in outShp.fields if f[0] == k) )
StopIteration

location: <unknown location>:-1

```

**Comment by HorribleGoat** [comment] 2020-03-20 07:26
The test data itself here is just random location I zoomed in on the Basemap and loaded in the areas OSM data for highways.

**Comment by HorribleGoat** [comment] 2020-03-20 07:48
Tested different ways and found that if I open Blender, import the addon, load basemap and OSM data I can export 1 working SHP, after that its the errors above.

Then tested opening Blender. importing the addon and loading the saved Blend with the data tested above and that resulted in same errors.

Further testing seems to indicate that opening new Blender instance, loading base map and exporting loaded road road shapes works but if I do any edits or anything else in Blender the exporting breaks.  I can move camera, that didnt break it, but just selecting any imported object and then exporting I get error message.

**Comment by HorribleGoat** [comment] 2020-03-20 07:57
One further observation: 
Loading basemap, picking random area, loading road data - Exporting: Works
selecting ramdom part/doing something else - Exporting: Errors out
Undoing back to the post road data loading state - Exporting: Works again

**Comment by HorribleGoat** [comment] 2020-03-20 08:00
Deselecting objects does not seem to affect the export.
Selecting just the map object does not affect export.
Selecting any of the road parts breaks the export.

**Comment by HorribleGoat** [comment] 2020-03-20 08:02
Anything custom made I have not been able to export at all.

**Comment by domlysz** [comment] 2020-03-20 08:33
ok can you retry with the last update https://github.com/domlysz/BlenderGIS/commit/5dbfa732816f682cd4f4c862ebaa6580535941fa ?

**Comment by HorribleGoat** [comment] 2020-03-20 08:59
Seems to behave the same. Following error pops up when I try to used saved .Blend or if I do anything in Blender after importing data.

```
Exception ignored in: <function Writer.__del__ at 0x0000021EE950A678>
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1104, in __del__
    self.close()
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1122, in close
    "with the number of shapes (%s)" % (self.recNum, self.shpNum))
BlenderGIS-master.core.lib.shapefile.ShapefileException: When saving both the dbf and shp file, the number of records (0) must correspond with the number of shapes (1)
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_export_shp.py", line 273, in execute
    if not any([f[0] == k for f in outShp.fields]):
StopIteration

location: <unknown location>:-1


```

**Comment by HorribleGoat** [comment] 2020-03-20 09:00
Is it possible I have some required component installed wrongly?

**Comment by domlysz** [comment] 2020-03-20 10:50
hum I can't reproduce the last error, do you have a blend file ?

To explain more the issue :

OSM tags are reported as object custom properties, then when exporting to shp these properties are written into attributes data.

You can check the custom props in the object properties panel
![image](https://user-images.githubusercontent.com/5639024/77156316-71cfa780-6a9f-11ea-89b4-88ec23912433.png)

Seems like you have an addon or something else that automatically write a special custom props to any object named armaObjProps.

![image](https://user-images.githubusercontent.com/5639024/77156908-a6902e80-6aa0-11ea-9c18-9955ffa9f68e.png)

This property represents a group of properties and so can't be written as it in the shapefile because it's not a number nor a string of characters.

If this property exist the script crash, I don't know when exactly this property is created but until it not exists the script will work as expected and after it will fails. That explain why the error seems to appears randomly.

So the workaround is very simple, we just need to ignore this kind of property. That's what the 2 last updates do. For now I don't understand why you still encounter an issue.

Also, I will change a little the exporters options because I find them confusing !

**Comment by HorribleGoat** [comment] 2020-03-22 20:38
The property is added by another addon yes and while I could disable it,  its a bit counter intuitive for any workflow. I do use the other one quite a lot. 

The export seems to be working now though, I'll test it some more. Perhaps something did not update right before I restarted my computer.

**Comment by HorribleGoat** [comment] 2020-03-22 20:40
Also just tested my completely custom made data and that seems to work too!

Thank you for your fast response and help!

**Comment by HorribleGoat** [comment] 2020-03-22 21:09
Ok so I also got the shp to import to the program Im using it for but only if I joined all the line mesh parts together as single object. Not a problem but I just wonder what could be different from exporting it from the collection.

Anyway the problem that arise is that each line imports as separate segments instead of contiunous line.

![image](https://user-images.githubusercontent.com/13536770/77260680-3c3ee000-6c92-11ea-8948-7f7c456b5d9d.png)

**Comment by domlysz** [comment] 2020-03-23 07:52
About the shapefile exporter, I've updated the operator options this weekend because it was confusing. I've also updated the wiki accordingly : https://github.com/domlysz/BlenderGIS/wiki/Shapefile-export

> The operator will **export the current selection or the specified collection** of objects
> 
> There are 2 different export modes:
> 
> - **Mesh to features** : each faces, lines or points of the mesh will be exported as new shapefile feature.
> - **Objects to features** : Each object will be exported as new shapefile feature, so if an object contains more than one face, line or point then multipart features will be produced.
> 
> If an object has custom properties, then they will be transposed in the shapefile's attributes table

If I understand correctly, the second question is about the reimporting in Blender the shp previously exported from OSM data ? In this case make sure to tick the **_merge duplicate vertices_** option in the addon preferences. Always import OSM or SHP data with the **_separate objects_** option and export to SHP with the mode **_objects to features_**.

**EDIT :** just testing the workflow and I realized there was an issue with how the merge duplicate option is handle when separate objects option is ticked. I've just fixed it both for OSM and SHP importers. I think it will be more straightforward now.

**Comment by HorribleGoat** [comment] 2020-03-24 23:25
Excellent thank you. I dont think I had the merge option on. I'll test it and report back.

**Comment by HorribleGoat** [comment] 2020-03-29 17:24
Sorry it took me so long to get back to you. Stuff came up and had not a chance to continue with this.

I just reinstalled the plugin from fresh master download but the split lines thing still persists on import.

Where are the export modes toggled?  I now made sure I have the merge option ticked in the settings but that does not seem to do anything on my end.

**Comment by HorribleGoat** [comment] 2020-03-29 19:16
![image](https://user-images.githubusercontent.com/13536770/77858226-c9da7c80-720a-11ea-9b50-1decd3acd403.png)

As you can see the import does not stitch the parts together. Or the export split each edge as separate parts to begin with.

**Comment by domlysz** [comment] 2020-03-31 08:46
Here the workflow :

In addon prefs tick *Merge duplicate option*

![Capture du 2020-03-31 10-28-42](https://user-images.githubusercontent.com/5639024/78005281-a2370180-733b-11ea-9a73-c5c60c70cc27.png)

Import OSM Data with the option *Separate objects*

![Capture du 2020-03-31 10-29-45](https://user-images.githubusercontent.com/5639024/78005324-b11db400-733b-11ea-8459-49fd75428d83.png)

Here the result, with a highway selected

![Capture du 2020-03-31 10-30-47](https://user-images.githubusercontent.com/5639024/78005377-c5fa4780-733b-11ea-85e2-7331464e40db.png)

Enter edit mode and try to move a node, it's merged

![Capture du 2020-03-31 10-31-02](https://user-images.githubusercontent.com/5639024/78005455-e0ccbc00-733b-11ea-85cd-5234b1808877.png)


All imported objects are put into a new collection named highway

![Capture du 2020-03-31 10-31-26](https://user-images.githubusercontent.com/5639024/78005491-efb36e80-733b-11ea-9351-03d0ea3c915c.png)

Now export in shapefile : operators options are embed into the file browser. Select your collection, the mode *objects to features* and the correct feature type.

![Capture du 2020-03-31 10-33-06](https://user-images.githubusercontent.com/5639024/78005803-62bce500-733c-11ea-87af-738b85aabce7.png)

Now clear the scene and reimport the shapefile with the *separate objects* option
![Capture du 2020-03-31 10-34-16](https://user-images.githubusercontent.com/5639024/78005874-7cf6c300-733c-11ea-9e11-cb7f508d21dc.png)

Same result as before : separate ways with merged vertices

![Capture du 2020-03-31 10-34-39](https://user-images.githubusercontent.com/5639024/78005949-9ac42800-733c-11ea-99d5-a3c46487a83b.png)
![Capture du 2020-03-31 10-34-50](https://user-images.githubusercontent.com/5639024/78005963-9dbf1880-733c-11ea-8898-0b5f6dddbb9d.png)

**Comment by HorribleGoat** [comment] 2020-04-01 01:32
Thanks for the explanation! I got the OSM imported data to work right after exporting, but my custom made vertex lines only work partly.

![image](https://user-images.githubusercontent.com/13536770/78090066-c3e2c800-73d1-11ea-97b5-b78280129406.png)

some verticles are connected but some are still not. 

Do you have any advice for this?

**Comment by domlysz** [comment] 2020-04-01 06:51
There is a threshold value used for merging duplicate vertices. The parameters is not exposed, but you can edit it [directly in the code](https://github.com/domlysz/BlenderGIS/blob/master/operators/io_import_osm.py#L318)

As you can see the value is very low (0.0001 meters) so you can try to increase it. But this low value should not be a problem if the vertices truly share the same coordinate. I suspect the non merged vertices come from a bad digit from the OSM side with vertices that were not properly snapping each other.

**Comment by HorribleGoat** [comment] 2020-04-01 08:54
Thanks I'll try that! 

Oh and this isnt stuff from OSM, just something I made myself. The verticles are all merged in the thing I made though.

**Comment by HorribleGoat** [comment] 2020-04-01 09:50
Tested the OSM importing - exporting again and edited the lines a bit to see if that makes any difference. 

Seems like the edits (movin, extruding more verticles) export ok. But I did notice not all parts from OSM export as whole either:

![image](https://user-images.githubusercontent.com/13536770/78123785-65d8d380-7417-11ea-8786-2a1be3daffd0.png)

**Comment by domlysz** [comment] 2020-04-02 15:26
Have you tick the automerge option when editing 
![image](https://user-images.githubusercontent.com/5639024/78252899-d7864f80-74f3-11ea-84e6-158c9cc679c8.png)

is it work if you increase the automerge distance a bit ?

**Comment by HorribleGoat** [comment] 2020-04-10 01:49
well the problem for me I think is that if the lines are split in the SHP, then the program I would like to use them will have them split up. 

And its faster to just draw the shapes there than to combine them there. Its pretty crappy terrain building tool for a game I like to mod and I was hoping to find a way to bypass the manual shape drawing there.

**Comment by HorribleGoat** [comment] 2020-04-10 02:05
Heres a sample SHP from that program. This one imports fine as connected into it but the import into Blender splits it up in some places:

[roads.zip](https://github.com/domlysz/BlenderGIS/files/4459477/roads.zip)
imported to blender:
![image](https://user-images.githubusercontent.com/13536770/78955275-73f9b480-7ae7-11ea-98ce-9074c51bc650.png)

And when I merge it in Blender back together and export it, this is how it imports back into the program.

![image](https://user-images.githubusercontent.com/13536770/78955728-cb4c5480-7ae8-11ea-868a-8b0b2001eac2.png)

As you can see it is unfortunately again in pieces.

**Comment by HorribleGoat** [comment] 2020-04-10 02:07
Now this might be something that anything can be done about. But I do appreciate greatly the time you have put in to answer me already!

**Comment by HorribleGoat** [comment] 2020-04-10 02:12
Oh new development! I accidentally hit the clear georeferencing button on the import dialog and this time the shapes did import as wholes:

![image](https://user-images.githubusercontent.com/13536770/78956059-ce941000-7ae9-11ea-9ad5-c900a6fe558f.png)

**Comment by domlysz** [comment] 2020-04-18 13:48
hum I suspect your scene CRS was in WGS84 so when importing the shp it reproject it to this system, but merging double typically fails with this system because coordinates are in degrees not meters. So you must just take car of projection you set for the scene and for the shp

For your export issue, the only way to reach what you want is by checking _separate objects_ when importing and then select _object to feature_ when exporting. This way is the only way to maintain the initial features organisations of the shapefile.

You must understand that a shapefile does not store the information like a mesh, Each shp is collection of feature of one unique type (point, line or polygone). One feature is a sequence of connecting points. A shapefile may respect some topology rules, for example 2 crossing may not be represented by one ony 1 feature, it will be a non sense. 2 features cannot truly share a point, if they have a point with the same location then this point must exists independently in each features.

On another hand there is no features in a mesh, for representing lines, a mesh store only edges not polylines, an edge connect only 2 points, but 2 edges can truly share the same point and in this case they will be connected. 

So, if you import without checking _separate objects_ then you get a whole unique mesh with all duplicate vertices merged or nothing merged, so you break the organisation of features an you break the topology. In this situation there is no way for the exporter to determine how to merge edges for reconstruct logical features from this mashup, so by default all edges are treated as single line and putted into a single multipart feature.

Maybe some improvements are possible but it’s a difficult puzzle, it's so much simple to just keep features as separate objects.

**Closed** 2020-11-25 11:09 UTC
