### ISSUE TITLE
Basemap crash

### ISSUE THREAD

**Issue by iblueyonder** [domlysz/BlenderGIS#107] opened 2018-04-12 17:03 UTC
I'm attempting to use the Basemap feature of BGIS in Blender 2.79 and no matter which provider I choose, the program crashes to desktop. I did manage to capture the error once, although it's in a screenshot (sorry, I wish it was written to a text file somewhere) - see attached.
![blender_gis_error](https://user-images.githubusercontent.com/9486718/38692504-8744180a-3e49-11e8-9e79-6010770ec597.jpg)

**Comment by iblueyonder** [comment] 2018-04-12 17:04
By the way, I have installed GDAL as recommended, and both "from osgeo import gdal" and "from osgeo import gdalnumeric" run without errors.

**Comment by iblueyonder** [comment] 2018-04-12 17:04
Also, my OS is Windows 10.

**Comment by fitzlibutz** [comment] 2018-06-20 08:02
Well, I see the same problem. Crash to desktop w/o any further notice. Win10; blender 2.79a.

**Comment by domlysz** [comment] 2018-06-20 09:14
is it the same error message than in the screenshoot (cannot initialize osr : +init=epsg:3857) ?

**Comment by fitzlibutz** [comment] 2018-06-20 17:36
Well, had a stupid typo-error in gdal path, which allegedly caused the crash to desktop. Maybe some kind of error handler can catch this?

Second, there seems to be numpy issue, too:
#    ImportError: numpy.core.multiarray failed to import
#    Can't download tile x0 y1
#    Can't download tile x0 y0
#    RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

Tried it with 2.78, 2.79 and 2.80, but all the same. Maybe some false setup on my machine? I do not install blender; using the zips.

Switched to a virtualbox with ubuntu 18.04 and compilation from source. But I am still struggling with gdal installed on the base system. After compiling blender; i have numpy but no gdal. in a python3 shell, gdal is working. keep on trying to understand what i missed up to now.

Anyway, thanks for this software! 
//Stefan

**Comment by iblueyonder** [comment] 2018-06-20 17:53
Is there any insight into my original problem? I still can't run the add-on at all in Blender 2.79.

**Comment by fitzlibutz** [comment] 2018-06-20 18:38
"Is there any insight into my original problem"
Let's state a definite maybe: as far as i can see, the error is caused by getOgrSpatialRef(), which is related somehow to the gdal installation.
I try to get a system - either win or lx - up and running, but i run on both platforms in problems with gdal. As domlysz stated years ago, gdal and blender seems to be tricky.
I guess if I get my box running, I should have a least a hint to get your working, too. But im no programmer...
//Stefan

**Comment by iblueyonder** [comment] 2018-06-20 19:31
It's frustrating because I've had the plug-in working on past Blender installations, and without nearly so many problems.

**Comment by fitzlibutz** [comment] 2018-06-20 19:47
From my point of view, it' not frustrating at all. I got a interesting piece of software provided by domlysz and a known difficult relation between blender and gdal. Let's face the challenge and help to improve both of them.
Beeing honest, I would prefer plug-and-play too, but this is not the way I would gather knowledge.
//Stefan

**Comment by iblueyonder** [comment] 2018-06-20 19:55
I'm glad you're not frustrated. From my point of view, I got a piece of software (for free, a fact that I deeply appreciate) that could fix a big problem I've been having with my modeling, but for some reason I can't figure out it won't work at all, and nobody seems to know why. I'm not a programmer, and I have no clue why this is happening, and countless Google searches have turned up nothing useful. Frustration seems like a natural reaction to all that.

**Comment by fitzlibutz** [comment] 2018-06-20 20:08
Let me describe the other way round: Years ago, I bought a US-Software for $2400 for 3d georeferencing ( from a self anounced "market leader") - and it was entirely crap.
gdal was developed by Frank and handed over to experienced people like Helena. 
When we ask the right questions, we will receive the helping answers. 
//Stefan

**Comment by bluecd** [comment] 2018-06-20 20:34
Hi, would it be reasonable to rewrite for Blender 2.8?

śr., 20 cze 2018, 21:47 użytkownik fitzlibutz <notifications@github.com>
napisał:

**Comment by domlysz** [comment] 2018-06-20 20:54
@iblueyonder can you try to execute the following statements line by line in the Blender Python console and tel me where it fails (if it fails) and what is the result of the print

```python
from osgeo import osr
prj = osr.SpatialReference()
r = prj.ImportFromProj4('+init=epsg:3857')
print(r)
```

@fitzlibutz why not using installation through PPA ? 

Do both of you really need GDAL functionnalities (the addon can run without) ?

@bluecd Blender 2.8 is not released...  the migration will be done when the time comes

**Comment by iblueyonder** [comment] 2018-06-20 21:03
> @domlysz when I run those commands in my Blender Python console it prints "0".

**Comment by domlysz** [comment] 2018-06-20 21:13
ok so it works as expected. Have you encounter the same error message than in april (ie "cannot initialize osr +init=epsg:3857) ?

**Comment by iblueyonder** [comment] 2018-06-20 21:15
@domlysz Yes, it happens every time I try to load a basemap.

**Comment by domlysz** [comment] 2018-06-20 21:17
is it an a new blank scene or an existing blend file that you reopen ?

**Comment by iblueyonder** [comment] 2018-06-20 21:18
I've tried it both ways. Both result in a Blender crash-to-desktop.

**Comment by domlysz** [comment] 2018-06-20 21:21
is it works if you switch the projection engine in the addon preferences to "built in" ?

**Comment by domlysz** [comment] 2018-06-20 21:30
ok and if you let "built" in for projection engine and switch image engine to "imageio" ?

if it crash to desktop, maybee you can't have enough time to see the error message ? If so you must run blender from a windows terminal to see all report messages

**Comment by iblueyonder** [comment] 2018-06-20 21:36
I'd like to run it from a Windows terminal. I tried calling Blender.exe from a windows command window, but even then I get no error message when it crashes. How can I capture the error info? That's been one of the most vexing things - not being able to see why it's crashing in the first place.

**Comment by domlysz** [comment] 2018-06-20 21:50
usually errors message will be printed in the terminal window that stay open after the crash. As I remember, a way to run blender in a Windows terminal : go to the install folder, then right click while maintaining shift key and choose "open terminal here", then type 'blender' to start the execution

More questions:
- is it works with Blender 2.78 ?
- have you tried with Blender stand alone zip package instead of installer ?

**Comment by iblueyonder** [comment] 2018-06-20 21:54
I tried that method for running Blender, but it doesn't maintain the console with the error. Once Blender crashes, it takes the console with it and there doesn't seem to be any trace left of the event I could use to trace. I'll try it in 2.78 and see if that helps.

**Comment by iblueyonder** [comment] 2018-06-20 22:05
I can confirm that on my system, using a stand-alone Blender 2.78c install without GDAL, the add-on works. That's a good start. Now I'll try adding GDAL support to that version and see what happens.

**Comment by domlysz** [comment] 2018-06-20 22:09
finally make some little progress !

**Comment by onerobotband** [comment] 2018-06-25 14:35
@domlysz 

from osgeo import osr
prj = osr.SpatialReference()
r = prj.ImportFromProj4('+init=epsg:3857')
print(r)

this returns the number 6 for me.

**Comment by onerobotband** [comment] 2018-06-25 14:57
first part of error message not copying to python text editor window in blender, this is the text copied (typed up!) from the error message pop-up:

Traceback (most recent call last):


File "C:\Users\orb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 644, in modal
self.progress = self.map.srv.report
File "C:\Users\orb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\modules\bpy_types.py", line 601, in __getattribute__
properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed

**Comment by domlysz** [comment] 2018-06-25 16:20
code error 6 refers to a general failure, no more clue. Is it works before trying to install GDAL ? If so it's an issue related to the gdal install

**Comment by domlysz** [comment] 2018-06-25 21:46
So as discussed in #91 it seems this issue come from missing GDAL_DATA environment variable. @iblueyonder can you confirm if for you setting this variable solve the problem?

**Comment by fitzlibutz** [comment] 2018-06-26 08:56
I'm not too happy with silent dependency checks, so I added some verbose output to the checkdeps.py file to find out what goes on in my system and which versions of code are in use. This works for me in W10; there may be further issues using __version__ or .VersionInfo().

checkdeps.py:

import os

print('\nINFO: check dependencies for addon BlenderGIS:\n')

#set variables to defined start value
if 0:
	HAS_GDAL = False
	HAS_NUMPY = False
	HAS_PYPROJ = False
	HAS_PIL = False
	HAS_IMGIO = False

# enable or disable tests
CHECK_SYS_PATH = 0
CHECK_GDAL = 1
CHECK_NUMPY = 1
CHECK_PYPROJ = 1
CHECK_PIL = 1
CHECK_IMAGEIO = 1

# enable for full path info
if CHECK_SYS_PATH:
	import sys
	print(sys.path,'\n')
	
#GDAL
if CHECK_GDAL:
	try:
		from osgeo import gdal
	except:
		HAS_GDAL = False
		print('WARNING: HAS_GDAL = False\n')
	else:
		HAS_GDAL = True
		print('INFO: HAS_GDAL = True; version = ',gdal.VersionInfo())
		print (gdal)
		print('GDAL_DATA = ',os.environ['GDAL_DATA'],'\n')
	
#NUMPY
if CHECK_NUMPY: 
	try:
		import numpy
	except:
		HAS_NUMPY = False
		print('WARNING: HAS_NUMPY = False\n')
	else:
		HAS_NUMPY = True
		print('INFO: HAS_NUMPY = True; version = ',numpy.__version__)
		print (numpy,'\n')
	
#PyProj
if CHECK_PYPROJ: 
	try:
		import pyproj
	except:
		HAS_PYPROJ = False
		print('WARNING: HAS_PYPROJ = False\n')
	else:
		HAS_PYPROJ = True
		print('INFO: HAS_PYPROJ = True; version = ',pyproj.VersionInfo())
		print (pyproj,'\n')

#PIL/Pillow
if CHECK_PIL:
	try:
		import PIL
	except:
		HAS_PIL = False
		print('WARNING: HAS_PIL = False\n')
	else:
		HAS_PIL = True
		print('INFO: HAS_PIL = True; version = ',PIL.VersionInfo())
		print (PIL,'\n')

#Imageio freeimage plugin
if CHECK_IMAGEIO:
	try:
		from .lib import imageio
		imageio.plugins._freeimage.get_freeimage_lib() #try to download freeimage lib
	except:
		HAS_IMGIO = False
		print('WARNING: HAS_IMGIO = False')
	else:
		HAS_IMGIO = True
		print('INFO: HAS_IMGIO = True; version = ',imageio.__version__)
		print (imageio,'\n')
	
print('\nINFO: end of check dependencies for addon BlenderGIS.\n')

**Comment by fitzlibutz** [comment] 2018-06-26 11:53
Why gdal?

Using a fresh unzip both 2.78c and 2.79b with cleared AppData and generic install of BlenderGIS_master, I tried to work with the built-in proj. engine:

WGS-84 asks for gdal when opening the basemap

Web-Mercator delivers OSM data - which is fine!

STRM uses epsg:4326 and gives no return data (as far as i can see from the source code)

My data environment is epsg:31468 (in/out), so it looks like gdal is mandatory. 

The error message from the inital post: 
"location: <unknown location>:-1"
appears too, but with no further reference.

**Comment by domlysz** [comment] 2018-06-26 13:52
You can also consider homogenize your data in QGIS before import them in Blender (same extent, projection, format...) .

I've updated the wiki for windows environment : https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL

Have you tried to setup GDAL_DATA environment variable? it solve the initial issue raised by iblueyonder

**Comment by domlysz** [comment] 2018-07-13 07:40
As the initial issue is now fixed, I close it. @fitzlibutz if you still encoutered difficulties making the addon properly working with GDAL please open a new one

**Closed by domlysz** 2018-07-13 07:40 UTC
