### ISSUE TITLE
Add compatibility with dxf importer

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#11] opened 2016-03-20 16:21 UTC
https://wiki.blender.org/index.php/User:Cnd/Extensions:2.6/Py/Scripts/Import-Export/DXF_Importer

it use pyproj to convert coords on the fly
SRID info is stored in scene

**Comment by mirlip** [comment] 2016-03-25 18:27
Would be awesome :)

**Comment by domlysz** [comment] 2016-06-06 17:14
In theory fixed with the new  _geoscene_ addon
https://github.com/domlysz/BlenderGIS/commit/4a2f2bd65eb00d31e4899f843a708ab609eeb786

need more testing here

**Comment by mirlip** [comment] 2016-06-06 20:30
I'll test as soon as possible and report :)

**Comment by mirlip** [comment] 2016-06-13 21:29
Tried to get a dxf and a shp to align, without success until now. I guess I choose the wrong srid in dxf importer. I chose wgs84, because actually dxfs have no projections, just a latitude and longitude? Any help appreciated :)

**Comment by domlysz** [comment] 2016-06-14 07:25
can you join the dxf ?

**Comment by mirlip** [comment] 2016-06-14 08:56
Here you have one building of the OSM file in the dxf file.
[test1.zip](https://github.com/domlysz/BlenderGIS/files/313506/test1.zip)
The shape file including this area can be found here : http://download.geofabrik.de/europe/germany/baden-wuerttemberg/freiburg-regbez-latest.shp.zip
I first imported the dxf, after installing pyproj to get the options in the dxf importer. The longitude and latitude after choosing wgs84 are correct in the scene custom properties. But the shape file import (using latest version of your addon and all needed python modules (gdal, etc...) is to small (it seems to be exactly 1 000 000 time to small).

**Comment by mirlip** [comment] 2016-06-14 09:36
After importing an OSM with blender GEO, I get the same problem of basemap not displaying and zooming out being disabled. I tried to find the "custom" option, but it seems to be removed in last version?

**Comment by domlysz** [comment] 2016-06-14 10:01
How this dxf was generated? the projection for this file is not wgs84. Your shapefile is in wgs84, source *.osm file also but not this dxf. Please use QGIS beforehand to harmonize your data into same projection, it's really  a better approach, you can't expect any magic alignment if you don't know how to define the projection of your data. Do you really want to work in Blender in longitude latitude, have all your measurement in degrees and lot of distortion along horizontal axis ??? I don't think it a good idea, so you need at first to choose a reliable projection system for your location, don't know what you commonly use in germany, maybee one of the lcc can be a good start
![selection_001](https://cloud.githubusercontent.com/assets/5639024/16038943/a2603b94-3227-11e6-9311-0b7f931de4f3.jpg)

**Comment by domlysz** [comment] 2016-06-14 10:09
lucky me, I found the projection for your dxf, it's Germany transverse mercator zone 3 !
![selection_002](https://cloud.githubusercontent.com/assets/5639024/16039202/d2cf8428-3228-11e6-8aee-3c6f83f3613f.jpg)

**Comment by mirlip** [comment] 2016-06-14 10:22
Hi domlysz,
The DXFs we get are directly from the town and are not projected (by us at least). We get them as-is. How did you find the projection? 
When I choose custom SRID in the dxf importer, then enter "31493" or "EPSG:31493" 
like in your picture, it says wrong SRID and stays red.
 ![problem dxf importer](https://cloud.githubusercontent.com/assets/12851284/16039472/53549600-322a-11e6-8130-ae0213f40ff8.PNG)
QGIS doesn't work, because their are 3D data in the original dxf, which are deleted by QGIS but are their when imported in Blender directly. It would be nice if you have some advice on how to make both addons work together.
The same problem happens with the OSM importer by the way. It seems I can't find a way to make the shape file importer take the georef from OSM/DXF into account.

**Comment by domlysz** [comment] 2016-06-14 10:38
Found it trying all germany proj in QGIS !

I know about this problem with 3d dxf export through QGIS, good news it seems it will be fixed in QGIS 2.16.

Have the same problem with 31493, the error come from pyproj which don't recognize it as valid EPSG code. Note that the SRIOD must be in the form `EPSG:32493`

![selection_003](https://cloud.githubusercontent.com/assets/5639024/16039886/c6085d4c-322c-11e6-8a81-c60fd748097e.jpg)

**Comment by domlysz** [comment] 2016-06-14 10:44
[here](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/data/epsg) the file used by pyproj to define projection, maybee if you found it on your system you can edit it to add 31493

**Comment by domlysz** [comment] 2016-06-14 10:55
On linux, I found this file in /usr/share/proj
I've edit it as follow :
![selection_006](https://cloud.githubusercontent.com/assets/5639024/16040337/3c748b5c-322f-11e6-8efe-673c88f06c08.jpg)

And now the code is correctly recognized in dxf importer

![selection_004](https://cloud.githubusercontent.com/assets/5639024/16040354/50084636-322f-11e6-8778-53fc96370903.jpg)

**Comment by domlysz** [comment] 2016-06-14 10:59
however don't know why, for me dxf importer does not set longitude latitude correctly

![selection_007](https://cloud.githubusercontent.com/assets/5639024/16040440/c8b2050e-322f-11e6-8f7e-78574e31adda.jpg)

**Comment by domlysz** [comment] 2016-06-14 11:07
About OSM importer, for now my tool is not compatible with Blender-geo, I've oppened a discussion about this [here](https://github.com/vvoovv/blender-geo/issues/22)

It's always possible to hack the thing forcing the scene SRID as explained [here](https://github.com/domlysz/BlenderGIS/issues/10), but I really want to solve this in a better way, so be patient !

**Comment by domlysz** [comment] 2016-06-14 12:07
oh found the problem, just forget to tick 'center geometry t oscene' in dxf importer

![selection_008](https://cloud.githubusercontent.com/assets/5639024/16042080/3422ad58-3239-11e6-94cf-db6a7545b7d5.jpg)

But longitude and latitude seems to be reversed

![selection_009](https://cloud.githubusercontent.com/assets/5639024/16042086/425b5c6c-3239-11e6-97bc-8a25d6fe3a3f.jpg)

**Comment by domlysz** [comment] 2016-06-14 12:13
you can type the following to revert latlon in blender python's console

```
import bpy
scn = bpy.context.scene
scn['longitude'], scn['latitude'] = scn['latitude'], scn['longitude']
```

**Comment by domlysz** [comment] 2016-06-14 12:15
now all is in place

![selection_010](https://cloud.githubusercontent.com/assets/5639024/16042307/69b3fe62-323a-11e6-97bf-3235dab5fad9.jpg)

don't know what the dxf polygon represents but the location seems good

**Comment by domlysz** [comment] 2016-06-14 12:17
same data in QGIS

![selection_011](https://cloud.githubusercontent.com/assets/5639024/16042396/bc504d88-323a-11e6-8bca-5cc9784bac27.jpg)

**Comment by domlysz** [comment] 2016-06-14 12:29
opened an issue about inverted lonlat

https://bitbucket.org/treyerl/io_import_scene_dxf/issues/8/inverted-longitude-latitude

**Comment by mirlip** [comment] 2016-06-14 12:36
Hi Domlysz,
Amazing :) I'm reproducing the steps you found, will report on it as soon as I'm ready :)

**Comment by mirlip** [comment] 2016-06-14 12:45
Ok, so I added the code to epsg, gave it to dxf as user defined with "center scene". Then I switched the long and lat, clicked on the chain in the GIS panel to recenter the origin (it was red with warning sign, it became blue), then imported the building.shp fro geofabrik, but it was still 1 000 000 times to small and there was no option to georeference at import time. What step did I miss?

**Comment by domlysz** [comment] 2016-06-14 12:48
shapefile is in wgs84 so you need to choose this projection to reproject it at import
![selection_012](https://cloud.githubusercontent.com/assets/5639024/16043262/17f23af8-323f-11e6-86ed-e2a656b08e54.jpg)

**Comment by mirlip** [comment] 2016-06-14 12:58
I have options for crs in the gis tab (tool panel) 
![crs](https://cloud.githubusercontent.com/assets/12851284/16043519/4abad610-3240-11e6-9ea6-02dbeca3734a.PNG)

but not during import
![options](https://cloud.githubusercontent.com/assets/12851284/16043523/4f60bd42-3240-11e6-91b9-068c4784094f.PNG)

I checked that I have the latest version installed and activated, and it's the case (6 of june 2016), but the UI for import seem like the old one....

**Comment by mirlip** [comment] 2016-06-14 13:00
All addons from this git are activated:
![activated addons](https://cloud.githubusercontent.com/assets/12851284/16043599/b0b5b4e4-3240-11e6-8123-086a364545a1.PNG)
and as said before, Pillow, Gdal and pyproj are installed and work (I can import them in python console)

**Comment by domlysz** [comment] 2016-06-14 13:06
thats strange maybee it found another old version elsewhere

try to remove the one you locate to see if blender still finds a shp importer

**Comment by mirlip** [comment] 2016-06-14 13:14
Although it said it takes the addon in the appdata/addon folder, it took it somewhere else. Now I have the new version but I get this:
`Read shapefile...
Feature type : Polygon
Data will be reprojected from EPSG:4326 to epsg:31493
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_shapefile\op_import_shp.py", line 339, in execute
    rprj = Reproj(shpCRS, geoscn.crs)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 127, in __init__
    self.crs1 = crs1.getOgrSpatialRef()
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 328, in getOgrSpatialRef
    raise ValueError('Cannot initialize osr : ' + self.proj4)
ValueError: Cannot initialize osr : +init=epsg:4326

location: E:\blender\2.77\scripts\modules\bpy\ops.py:187

location: E:\blender\2.77\scripts\modules\bpy\ops.py:187
Error: Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_shapefile\op_import_shp.py", line 339, in execute
    rprj = Reproj(shpCRS, geoscn.crs)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 127, in __init__
    self.crs1 = crs1.getOgrSpatialRef()
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 328, in getOgrSpatialRef
    raise ValueError('Cannot initialize osr : ' + self.proj4)
ValueError: Cannot initialize osr : +init=epsg:4326

location: E:\blender\2.77\scripts\modules\bpy\ops.py:187

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_shapefile\op_import_shp.py", line 210, in execute
    extrusionAxis=self.extrusionAxis, separateObjects=self.separateObjects)
  File "E:\blender\2.77\scripts\modules\bpy\ops.py", line 187, in
 __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_shapefile\op_import_shp.py", line 339, in execute
    rprj = Reproj(shpCRS, geoscn.crs)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 127, in __init__
    self.crs1 = crs1.getOgrSpatialRef()
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\proj.py", line 328, in getOgrSpatialRef
    raise ValueError('Cannot initialize osr : ' + self.proj4)
ValueError: Cannot initialize osr : +init=epsg:4326

location: E:\blender\2.77\scripts\modules\bpy\ops.py:187`

**Comment by mirlip** [comment] 2016-06-14 13:15
after restarting blender, it works, was due to the activation just after reinstalling it seems...

**Comment by mirlip** [comment] 2016-06-14 13:26
Whoho, it works :) It has a slight shift on x and y
![shift](https://cloud.githubusercontent.com/assets/12851284/16044153/8119cef2-3243-11e6-8280-43c8e6ff6cd4.PNG)
but it's certainly due to the limited precision of the copy paste to invert the long and lat, Blender only copies the first 5 digits. So the dxf importer has to be fixed first I guess.
Really impressive :)

The steps for documentation until it becomes easier:
- install pyproj like gdal with pip
- add the epsg code to the epsg file from pyproj
- import dxf with user defined srid (same for import and scene srid)
- invert long and lat
- activate this georef in the toolpanel -> gis tab
- import with shop importer by selecting appropriate CRS

Questions remains on how to find the epsg code/crs of the different files without trial and error.

Really a great step forward to stay in Blender as much as possible when working :)

**Comment by kikislater** [comment] 2016-06-14 13:35
Whaooh ! That's an amazing stuff Dominique. 
Now we could object 3d object georeferenced import and export to GIS <=> Blender !

**Comment by domlysz** [comment] 2016-06-14 13:56
Glad it finally works !

Geodata are nearly unusable if you don't know what's the projection. For shp open it in QGIS and most of the case the projection will be automatically detected, but for dxf there is no magic, asking the person who produce the drawing is probably the better way ...

**Comment by kikislater** [comment] 2016-06-14 14:05
Yeah but it's not a GIS problem, it's a common dao problem.
I don't follow which module you are using but seems to be interesting ... ok i see pillow, gdal and pyproj, nice !
So it seems to close this issue also : https://github.com/domlysz/BlenderGIS/issues/7

**Comment by domlysz** [comment] 2016-06-14 14:25
not really, as I know dxf export does not take georef into account.

I've added a wiki about the [new georef managment](https://github.com/domlysz/BlenderGIS/wiki/Gereferencing-management) in BlenderGIS, hope it help.

I try as much as possible to keep the addon usable without dependency, for reprojection it can use gdal or pyproj depends on what it found, but if there is none of these module it use http://epsg.io web service.

The new basemaps addon still depends on pillow, but I currently studying alternatives for an easier install

**Comment by mirlip** [comment] 2016-06-14 18:08
Do you know if the slight translation (about 100m) is really due to the copy-paste precision or if it's due to something else?

**Comment by mirlip** [comment] 2016-06-14 20:40
I have another problem. Actually, the code for the dxf importer, using pyproj, is "ESRI:31493" and not "EPSG:31493" Nuber is right, but ESRI not EPSG. Then it works without modifying the epsg file. Problem is, blender GIS can't move origin when using ESRI instead of EPSG.
So at the moment, their are 3 steps:
 - switch lat and long: will hopefully be fixed upstream
 - manually edit code from ESRI: to EPSG: could be fixed to also recognise ESRI: or at least automatically translate ?
- click on the chain to recalculate origin: could be automated?

**Comment by domlysz** [comment] 2016-06-15 08:08
I suspect the translation come from a bad transformation accuracy because 31493 is based on a different ellipsoid than wgs84. Also, if you switch latlon throughPython console all the digits will be used and there will no accuracy lost.

There is an interesting comment on http://epsg.io/ about 31493, it seems it's an alias (from ESRI?) to [EPSG:31467](http://epsg.io/31467). Moreover, the definition of 31467 is the same of 31493 except that it add a transformation parameters (7 parameters matrix +towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7).

So this one will give a mutch better transformation accuracy, try it!

**Comment by domlysz** [comment] 2016-06-15 09:08
Also I got really better alignment using Bing photo instead of Google. Not surprising at all because most on OSM buildings data come from a digitalization based on Bing arial photo (there is an accord between OSM and Microsoft). 

What is the best between Google and Bing, hard to say, I don't use any of both as reliable reference for large scale because sometimes the ortho rectification is really bad. Sources from local institution are generally much better.

![selection_014](https://cloud.githubusercontent.com/assets/5639024/16073679/6162d67c-32e7-11e6-834f-93470b8418ff.jpg)

**Comment by kikislater** [comment] 2016-06-15 12:46
Both are not accurate I can confirm. 
Precision 3 to 30m for google. It depends on the location : sometimes good, sometimes not. Also, it's important to notice that Google coordinates does not go below 0.1m

**Comment by mirlip** [comment] 2016-06-15 18:59
Awesome epsg code Domlysz :) Much better and prevent using esri code :) But maybe for some person it would make sense to also support the esri codes if it's not too hard to implement.
Really awesome addon you do :)

**Comment by domlysz** [comment] 2016-06-15 19:47
Esri code work for me, where is the problem?

**Comment by mirlip** [comment] 2016-06-15 20:37
when I import a dxf file with an esri code, then try in the gis panel to reacalculate origin (with the chain icon) it fails. With an epsg code, it works.
Error: `Cannot initialize osr : +init=esri:31493`

**Comment by domlysz** [comment] 2016-06-16 10:20
problem come from gdal installation here, maybee it can't found the file named *esri* in gdal_data or proj_data

**Comment by mirlip** [comment] 2016-06-16 15:32
strange is that it finds GDAL_DATA directory. I tried to remove the environment variable and it made blender crash. So the variable is correctly set, otherwise it would also crash. And the epsg file is in the same directory like the esri one.

**Comment by mirlip** [comment] 2016-06-16 18:09
Apropos, the path to the GDAL_DATA directory for people installing through pip on windows 2.7x\python\lib\site-packages\osgeo\data\gdal could be added to the wiki with how to add it to the environment variables. If you give me the right to modify the wiki, I can help you if you want.

**Comment by domlysz** [comment] 2016-06-17 16:52
but seems your GDAL_DATA points to the osgeo directory on C:, isn't it ?

**Comment by mirlip** [comment] 2016-06-17 19:03
Actually not, I broke the system gdal to make the blender one work. I don't need QGIS really anymore slowly thanks to your plugin.

**Comment by domlysz** [comment] 2016-06-19 10:49
ok you can edit the wiki, I've tested it on windows and aslo need to set gdal_data

I close this issue, compatibility with dxf importer seems ok

**Closed** 2016-06-19 10:49 UTC
Labels: enhancement

**Comment by mirlip** [comment] 2016-06-19 15:12
I tried to edit the wiki, but it seems I must have it as repository to be allowed to do it?
